# This is a comment line

#define variables so it is easier to make changes
CC=gcc
CFLAGS=-g -Wall -std=c99
TARGETS=ex-factorial

all: $(TARGETS)

oddSum: oddSum.c
	$(CC) $(CFLAGS) -o oddSum oddSum.c
2d-walk: 2d-walk.c
	$(CC) $(CFLAGS) -o 2d-walk 2d-walk.c
clean:
	rm -rf *.o *~ $(TARGETS) a.out


